"""Leo Rover articulation config (Phase 1 stub).

Phase 1 deliverable: a LeoRoverArticulationCfg that points to a USD asset
generated from the PyBullet URDF (leo_robot_1_ros2_shared.urdf).

The URDF source file should be copied here under source/ before running
the URDF→USD converter:

    leorover_isaac/assets/leo_rover/
        source/
            leo_robot.urdf         (copied from PyBullet repo)
            macros.xacro           (copied from PyBullet repo)
            *.dae, *.stl           (copied mesh files)
        leo_robot.usd              (generated by convert_urdf.py, gitignored)
        __init__.py                (this file — exports LeoRoverArticulationCfg)

The articulation config will pattern-match Isaac Lab's existing
wheeled-robot configs. Reference implementations to copy from:
    isaaclab_assets/robots/carter.py
    isaaclab_assets/robots/husky.py
"""

from __future__ import annotations

# Real implementation imports:
#   from isaaclab.assets import ArticulationCfg
#   from isaaclab.actuators import VelocityActuatorCfg
#   from isaaclab.sim import UsdFileCfg
#   from isaaclab.utils.assets import ISAACLAB_NUCLEUS_DIR

__all__ = ["LEO_ROVER_CFG"]

# Stub — Phase 1 fills this in.
LEO_ROVER_CFG = None
